version: "3.7"
services:

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017

  server:
    build: ./
    restart: always
    ports:
      - 8080:80
    depends_on:
      - mongo