version: "3.7"
services:

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
        
  influxdb:
    image: influxdb:2.0.7
    container_name: influxdb
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminadmin
      - DOCKER_INFLUXDB_INIT_ORG=smart-farm
      - DOCKER_INFLUXDB_INIT_BUCKET=smart-farm
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=smart-farm-admin-token
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb
  
  server:
    build: ./
    restart: always
    ports:
      - 8080:80
    depends_on:
      - mongo
      - influxdb

volumes:
  influxdb_data: {}